spring:
  application:
    name: system-service
  cloud:
    nacos:
      server-addr: 192.168.163.129:8848
      discovery:
        namespace: learnonlinedev
        group: xuecheng-plus-project
      config:
        namespace: learnonlinedev
        group: xuecheng-plus-project
        file-extension: yaml
        refresh-enabled: true
        shared-configs:
          - data-id: log-dev.yaml
            group: learnonlinedev

  profiles:
    active: dev


