<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>learnOnline-parent</artifactId>
        <groupId>com.xuecheng</groupId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../learnOnline-parent</relativePath>
    </parent>
    <artifactId>learnOnline-system</artifactId>
    <name>learnOnline-system</name>
    <description>learnOnline-system</description>
    <packaging>pom</packaging>

    <modules>
        <module>learnOnline-system-api</module>
        <module>learnOnline-system-service</module>
        <module>learnOnline-system-model</module>
    </modules>
</project>
